name: slash_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.3
  flutter_riverpod: any
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  google_fonts: ^6.1.0
  highlight: ^0.7.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  url_launcher: ^6.3.2

uni_links:
  git:
    url: https://github.com/jaweaver/uni_links.git
    ref: namespace-fix

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/slash.png
    - assets/slash2.png

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/slash.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/slash.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/slash.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/slash.png"
